# Production Environment Configuration
# For AWS Bedrock AgentCore Runtime deployment

environment: production
region: us-west-2

# Agent Configuration
agents:
  orchestrator:
    name: interlinked-aos-prod-orchestrator
    model: anthropic.claude-3-5-sonnet-20241022-v2:0
    description: "Main orchestrator agent for routing user queries"

  graph:
    name: interlinked-aos-prod-graph-agent
    model: anthropic.claude-3-5-sonnet-20241022-v2:0
    description: "Handles graph read and search operations"

  analyzer:
    name: interlinked-aos-prod-analyzer-agent
    model: anthropic.claude-3-5-sonnet-20241022-v2:0
    description: "Performs analytics on graph data"

  extractor:
    name: interlinked-aos-prod-extractor-agent
    model: anthropic.claude-3-5-sonnet-20241022-v2:0
    description: "Manages data ingestion with controlled writes"

  admin:
    name: interlinked-aos-prod-admin-agent
    model: anthropic.claude-3-5-sonnet-20241022-v2:0
    description: "Handles privileged administrative operations"

# Neo4j Configuration
neo4j:
  connection_mode: gateway  # Use Gateway for production
  timeout: 30
  max_retry: 3
  gateway_endpoint: ${GATEWAY_ENDPOINT}

# AgentCore Features
agentcore:
  memory:
    enabled: true
    retention_days: 30

  observability:
    enabled: true
    trace_model_calls: true
    trace_tool_calls: true
    log_level: INFO
    cloudwatch_log_group: /aws/bedrock/agentcore/interlinked-aos-prod

  identity:
    enabled: true
    provider: cognito
    user_pool_id: ${COGNITO_USER_POOL_ID}
    client_id: ${COGNITO_CLIENT_ID}

  gateway:
    enabled: true
    oauth_authorizer: true
    rate_limiting:
      requests_per_second: 100
      burst: 200

# Security
security:
  secrets_provider: secretsmanager
  secret_name: interlinked-aos-prod
  allowed_node_labels:
    - Person
    - Organization
    - Project
    - Technology
    - Resource
  allowed_relationship_types:
    - WORKS_AT
    - MANAGES
    - PARTICIPATES_IN
    - USES
    - RELATES_TO

# Performance
performance:
  query_timeout: 30
  max_query_complexity: 1000
  result_pagination_size: 50
  max_result_size: 1000

# Monitoring & Alarms
monitoring:
  cloudwatch_namespace: Interlinked/AOS
  alarms:
    error_rate_threshold: 0.02  # 2%
    latency_p99_threshold: 5000  # 5 seconds

# IAM Roles
iam:
  agent_execution_role: arn:aws:iam::${AWS_ACCOUNT_ID}:role/interlinked-aos-agent-execution
  gateway_lambda_role: arn:aws:iam::${AWS_ACCOUNT_ID}:role/interlinked-aos-gateway-lambda
